# Generated by Django 3.1.1 on 2020-09-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_refund_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
